In [8]:
import pandas as pd

df = pd.read_csv('data/heart.csv')

cross_tab = pd.crosstab(df['cp'], df['target'], normalize='index') *100
cross_tab.columns = ['No Disease', 'Disease']
cross_tab

,No Disease,Disease
cp,,
0,72.727273,27.272727
1,18.000000,82.000000
2,20.689655,79.310345
3,30.434783,69.565217


### سوال 28
'''
برای ویژگی cp (نوع درد قفسه سینه):

کدام دسته بیشترین ارتباط را با بیماری دارد؟
'''

# تحلیل
'''
cross_tab = pd.crosstab(df['cp'], df['target'], normalize='index') *100
یک جدول تقاطعی می سازه
df['cp']
سطر های جدول
df['target']
ستون های جدول
normalize='index'
نرمال سازی براساس سطر
*100
ضربدر ۱۰۰


کاربرد:
به ما میگه کدوم دسته مهم تره
ارتباط بین ویژگی ها و هدف رو نشون میده
به تصمیم گیری برای مراحل مدل سازی کمک میکنه
'''

# خروجی
'''
cp=0 از ۲۳ نفر با cp=0، ۷۲.۷% بیماری ندارند و ۲۷.۲% بیماری دارند
cp=1 از ۵۰ نفر با cp=1، ۱۸% بیماری ندارند و ۸۲% بیماری دارند ← بیشترین ارتباط
cp=2 از ۸۶ نفر با cp=2، ۲۰.۶% بیماری ندارند و ۷۹.۳% بیماری دارند
cp=3 از ۱۴۴ نفر با cp=3، ۳۰.۴% بیماری ندارند و ۶۹.۵% بیماری دارند
Cp1
بیشترین ارتباط رو با بیماری داره
'''